version: '3'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks: 
      yana:
    ports:
      - "8282:90"
    restart: always

  php:
    build: 
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    depends_on:
      - database
    networks:
      yana:

  database:
    image: mysql:latest
    volumes:
      - ./docker/db:/docker-entrypoint-initdb.d/
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "yana"
      MYSQL_USER: "yana"
      MYSQL_PASSWORD: "yana"
      MYSQL_DATABASE: "yana"
    networks:
      yana:
    ports:
      - 3306:3306
      
networks:
  yana:
